
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/service_data
    username: root
    password: 1234

---

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

---

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.yunsu1021.boardProject2
